// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"
	"database/sql"
)

const cancelBooking = `-- name: CancelBooking :one
UPDATE bookings
SET status = 'CANCELLED'
WHERE id = $1
RETURNING
    id, journey_id, seat_id, board_station_id, alight_station_id,
    board_sequence, alight_sequence, passenger_name, passenger_email,
    fare, status, created_at
`

type CancelBookingRow struct {
	ID              string       `json:"id"`
	JourneyID       string       `json:"journey_id"`
	SeatID          string       `json:"seat_id"`
	BoardStationID  string       `json:"board_station_id"`
	AlightStationID string       `json:"alight_station_id"`
	BoardSequence   int32        `json:"board_sequence"`
	AlightSequence  int32        `json:"alight_sequence"`
	PassengerName   string       `json:"passenger_name"`
	PassengerEmail  string       `json:"passenger_email"`
	Fare            string       `json:"fare"`
	Status          string       `json:"status"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

func (q *Queries) CancelBooking(ctx context.Context, id string) (CancelBookingRow, error) {
	row := q.db.QueryRowContext(ctx, cancelBooking, id)
	var i CancelBookingRow
	err := row.Scan(
		&i.ID,
		&i.JourneyID,
		&i.SeatID,
		&i.BoardStationID,
		&i.AlightStationID,
		&i.BoardSequence,
		&i.AlightSequence,
		&i.PassengerName,
		&i.PassengerEmail,
		&i.Fare,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    journey_id, seat_id, board_station_id, alight_station_id,
    board_sequence, alight_sequence, passenger_name, passenger_email, fare
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING
    id, journey_id, seat_id, board_station_id, alight_station_id,
    board_sequence, alight_sequence, passenger_name, passenger_email,
    fare, status, created_at
`

type CreateBookingParams struct {
	JourneyID       string `json:"journey_id"`
	SeatID          string `json:"seat_id"`
	BoardStationID  string `json:"board_station_id"`
	AlightStationID string `json:"alight_station_id"`
	BoardSequence   int32  `json:"board_sequence"`
	AlightSequence  int32  `json:"alight_sequence"`
	PassengerName   string `json:"passenger_name"`
	PassengerEmail  string `json:"passenger_email"`
	Fare            string `json:"fare"`
}

type CreateBookingRow struct {
	ID              string       `json:"id"`
	JourneyID       string       `json:"journey_id"`
	SeatID          string       `json:"seat_id"`
	BoardStationID  string       `json:"board_station_id"`
	AlightStationID string       `json:"alight_station_id"`
	BoardSequence   int32        `json:"board_sequence"`
	AlightSequence  int32        `json:"alight_sequence"`
	PassengerName   string       `json:"passenger_name"`
	PassengerEmail  string       `json:"passenger_email"`
	Fare            string       `json:"fare"`
	Status          string       `json:"status"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.JourneyID,
		arg.SeatID,
		arg.BoardStationID,
		arg.AlightStationID,
		arg.BoardSequence,
		arg.AlightSequence,
		arg.PassengerName,
		arg.PassengerEmail,
		arg.Fare,
	)
	var i CreateBookingRow
	err := row.Scan(
		&i.ID,
		&i.JourneyID,
		&i.SeatID,
		&i.BoardStationID,
		&i.AlightStationID,
		&i.BoardSequence,
		&i.AlightSequence,
		&i.PassengerName,
		&i.PassengerEmail,
		&i.Fare,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAvailableSeats = `-- name: GetAvailableSeats :many
SELECT s.id, s.coach_id, s.seat_number, s.row_num, s.col_num
FROM seats s
JOIN coaches c ON c.id = s.coach_id
WHERE c.coach_type_id = $1
AND s.id NOT IN (
    SELECT b.seat_id
    FROM bookings b
    WHERE b.journey_id = $2
    AND b.status = 'CONFIRMED'
    AND b.board_sequence < $4
    AND b.alight_sequence > $3
)
ORDER BY s.row_num, s.col_num
`

type GetAvailableSeatsParams struct {
	CoachTypeID    string `json:"coach_type_id"`
	JourneyID      string `json:"journey_id"`
	AlightSequence int32  `json:"alight_sequence"`
	BoardSequence  int32  `json:"board_sequence"`
}

func (q *Queries) GetAvailableSeats(ctx context.Context, arg GetAvailableSeatsParams) ([]Seat, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableSeats,
		arg.CoachTypeID,
		arg.JourneyID,
		arg.AlightSequence,
		arg.BoardSequence,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Seat
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.SeatNumber,
			&i.RowNum,
			&i.ColNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooking = `-- name: GetBooking :one
SELECT
    id, journey_id, seat_id, board_station_id, alight_station_id,
    board_sequence, alight_sequence, passenger_name, passenger_email,
    fare, status, created_at
FROM bookings
WHERE id = $1
`

type GetBookingRow struct {
	ID              string       `json:"id"`
	JourneyID       string       `json:"journey_id"`
	SeatID          string       `json:"seat_id"`
	BoardStationID  string       `json:"board_station_id"`
	AlightStationID string       `json:"alight_station_id"`
	BoardSequence   int32        `json:"board_sequence"`
	AlightSequence  int32        `json:"alight_sequence"`
	PassengerName   string       `json:"passenger_name"`
	PassengerEmail  string       `json:"passenger_email"`
	Fare            string       `json:"fare"`
	Status          string       `json:"status"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

func (q *Queries) GetBooking(ctx context.Context, id string) (GetBookingRow, error) {
	row := q.db.QueryRowContext(ctx, getBooking, id)
	var i GetBookingRow
	err := row.Scan(
		&i.ID,
		&i.JourneyID,
		&i.SeatID,
		&i.BoardStationID,
		&i.AlightStationID,
		&i.BoardSequence,
		&i.AlightSequence,
		&i.PassengerName,
		&i.PassengerEmail,
		&i.Fare,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listBookingsByJourney = `-- name: ListBookingsByJourney :many
SELECT
    id, journey_id, seat_id, board_station_id, alight_station_id,
    board_sequence, alight_sequence, passenger_name, passenger_email,
    fare, status, created_at
FROM bookings
WHERE journey_id = $1
ORDER BY created_at
`

type ListBookingsByJourneyRow struct {
	ID              string       `json:"id"`
	JourneyID       string       `json:"journey_id"`
	SeatID          string       `json:"seat_id"`
	BoardStationID  string       `json:"board_station_id"`
	AlightStationID string       `json:"alight_station_id"`
	BoardSequence   int32        `json:"board_sequence"`
	AlightSequence  int32        `json:"alight_sequence"`
	PassengerName   string       `json:"passenger_name"`
	PassengerEmail  string       `json:"passenger_email"`
	Fare            string       `json:"fare"`
	Status          string       `json:"status"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

func (q *Queries) ListBookingsByJourney(ctx context.Context, journeyID string) ([]ListBookingsByJourneyRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByJourney, journeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsByJourneyRow
	for rows.Next() {
		var i ListBookingsByJourneyRow
		if err := rows.Scan(
			&i.ID,
			&i.JourneyID,
			&i.SeatID,
			&i.BoardStationID,
			&i.AlightStationID,
			&i.BoardSequence,
			&i.AlightSequence,
			&i.PassengerName,
			&i.PassengerEmail,
			&i.Fare,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
