// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coaches.sql

package db

import (
	"context"
)

const getCoach = `-- name: GetCoach :one
SELECT id, coach_number, coach_type_id
FROM coaches
WHERE id = $1
`

func (q *Queries) GetCoach(ctx context.Context, id string) (Coach, error) {
	row := q.db.QueryRowContext(ctx, getCoach, id)
	var i Coach
	err := row.Scan(&i.ID, &i.CoachNumber, &i.CoachTypeID)
	return i, err
}

const listCoachesByType = `-- name: ListCoachesByType :many
SELECT id, coach_number, coach_type_id
FROM coaches
WHERE coach_type_id = $1
ORDER BY coach_number
`

func (q *Queries) ListCoachesByType(ctx context.Context, coachTypeID string) ([]Coach, error) {
	rows, err := q.db.QueryContext(ctx, listCoachesByType, coachTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coach
	for rows.Next() {
		var i Coach
		if err := rows.Scan(&i.ID, &i.CoachNumber, &i.CoachTypeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
