// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coach_types.sql

package db

import (
	"context"
)

const getCoachType = `-- name: GetCoachType :one
SELECT id, name, is_reserved, seat_capacity, fare_multiplier
FROM coach_types
WHERE id = $1
`

func (q *Queries) GetCoachType(ctx context.Context, id string) (CoachType, error) {
	row := q.db.QueryRowContext(ctx, getCoachType, id)
	var i CoachType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsReserved,
		&i.SeatCapacity,
		&i.FareMultiplier,
	)
	return i, err
}

const listCoachTypes = `-- name: ListCoachTypes :many
SELECT id, name, is_reserved, seat_capacity, fare_multiplier
FROM coach_types
ORDER BY name
`

func (q *Queries) ListCoachTypes(ctx context.Context) ([]CoachType, error) {
	rows, err := q.db.QueryContext(ctx, listCoachTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachType
	for rows.Next() {
		var i CoachType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsReserved,
			&i.SeatCapacity,
			&i.FareMultiplier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
