// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Booking struct {
	ID              string       `json:"id"`
	JourneyID       string       `json:"journey_id"`
	SeatID          string       `json:"seat_id"`
	BoardStationID  string       `json:"board_station_id"`
	AlightStationID string       `json:"alight_station_id"`
	BoardSequence   int32        `json:"board_sequence"`
	AlightSequence  int32        `json:"alight_sequence"`
	StationRange    interface{}  `json:"station_range"`
	PassengerName   string       `json:"passenger_name"`
	PassengerEmail  string       `json:"passenger_email"`
	Fare            string       `json:"fare"`
	Status          string       `json:"status"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

type Coach struct {
	ID          string `json:"id"`
	CoachNumber string `json:"coach_number"`
	CoachTypeID string `json:"coach_type_id"`
}

type CoachType struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	IsReserved   bool   `json:"is_reserved"`
	SeatCapacity int32  `json:"seat_capacity"`
}

type Route struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Origin      string `json:"origin"`
	Destination string `json:"destination"`
}

type Seat struct {
	ID         string `json:"id"`
	CoachID    string `json:"coach_id"`
	SeatNumber string `json:"seat_number"`
	RowNum     int32  `json:"row_num"`
	ColNum     int32  `json:"col_num"`
}

type Station struct {
	ID                   string `json:"id"`
	RouteID              string `json:"route_id"`
	Name                 string `json:"name"`
	SequenceOrder        int32  `json:"sequence_order"`
	DistanceFromOriginKm string `json:"distance_from_origin_km"`
}

type TrainJourney struct {
	ID         string    `json:"id"`
	ScheduleID string    `json:"schedule_id"`
	TravelDate time.Time `json:"travel_date"`
	Status     string    `json:"status"`
}

type TrainSchedule struct {
	ID            string    `json:"id"`
	TrainNumber   string    `json:"train_number"`
	RouteID       string    `json:"route_id"`
	DepartureTime time.Time `json:"departure_time"`
}

type Waitlist struct {
	ID              string       `json:"id"`
	JourneyID       string       `json:"journey_id"`
	SeatID          string       `json:"seat_id"`
	BoardStationID  string       `json:"board_station_id"`
	AlightStationID string       `json:"alight_station_id"`
	BoardSequence   int32        `json:"board_sequence"`
	AlightSequence  int32        `json:"alight_sequence"`
	PassengerName   string       `json:"passenger_name"`
	PassengerEmail  string       `json:"passenger_email"`
	Status          string       `json:"status"`
	CreatedAt       sql.NullTime `json:"created_at"`
}
