// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	CancelBooking(ctx context.Context, id string) (CancelBookingRow, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error)
	CreateWaitlistEntry(ctx context.Context, arg CreateWaitlistEntryParams) (Waitlist, error)
	GetAvailableSeats(ctx context.Context, arg GetAvailableSeatsParams) ([]Seat, error)
	GetBooking(ctx context.Context, id string) (GetBookingRow, error)
	GetCoach(ctx context.Context, id string) (Coach, error)
	GetCoachType(ctx context.Context, id string) (CoachType, error)
	GetJourney(ctx context.Context, id string) (TrainJourney, error)
	GetJourneyByScheduleAndDate(ctx context.Context, arg GetJourneyByScheduleAndDateParams) (TrainJourney, error)
	GetRoute(ctx context.Context, id string) (Route, error)
	GetRouteByCode(ctx context.Context, code string) (Route, error)
	GetSchedule(ctx context.Context, id string) (TrainSchedule, error)
	GetScheduleByTrainNumber(ctx context.Context, trainNumber string) (TrainSchedule, error)
	GetSeat(ctx context.Context, id string) (Seat, error)
	GetStation(ctx context.Context, id string) (Station, error)
	GetWaitlistEntry(ctx context.Context, id string) (Waitlist, error)
	ListBookingsByJourney(ctx context.Context, journeyID string) ([]ListBookingsByJourneyRow, error)
	ListCoachTypes(ctx context.Context) ([]CoachType, error)
	ListCoachesByType(ctx context.Context, coachTypeID string) ([]Coach, error)
	ListJourneysByDate(ctx context.Context, travelDate time.Time) ([]TrainJourney, error)
	ListRoutes(ctx context.Context) ([]Route, error)
	ListSchedulesByRoute(ctx context.Context, routeID string) ([]TrainSchedule, error)
	ListSeatsByCoach(ctx context.Context, coachID string) ([]Seat, error)
	ListStationsByRoute(ctx context.Context, routeID string) ([]Station, error)
	ListWaitlistByJourney(ctx context.Context, journeyID string) ([]Waitlist, error)
	UpdateWaitlistStatus(ctx context.Context, arg UpdateWaitlistStatusParams) (Waitlist, error)
}

var _ Querier = (*Queries)(nil)
