// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"
)

const getRoute = `-- name: GetRoute :one
SELECT id, name, code, origin, destination
FROM routes
WHERE id = $1
`

func (q *Queries) GetRoute(ctx context.Context, id string) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRoute, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Origin,
		&i.Destination,
	)
	return i, err
}

const getRouteByCode = `-- name: GetRouteByCode :one
SELECT id, name, code, origin, destination
FROM routes
WHERE code = $1
`

func (q *Queries) GetRouteByCode(ctx context.Context, code string) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRouteByCode, code)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Origin,
		&i.Destination,
	)
	return i, err
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, name, code, origin, destination
FROM routes
ORDER BY name
`

func (q *Queries) ListRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Origin,
			&i.Destination,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
