// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seats.sql

package db

import (
	"context"
)

const getSeat = `-- name: GetSeat :one
SELECT id, coach_id, seat_number, row_num, col_num
FROM seats
WHERE id = $1
`

func (q *Queries) GetSeat(ctx context.Context, id string) (Seat, error) {
	row := q.db.QueryRowContext(ctx, getSeat, id)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.SeatNumber,
		&i.RowNum,
		&i.ColNum,
	)
	return i, err
}

const listSeatsByCoach = `-- name: ListSeatsByCoach :many
SELECT id, coach_id, seat_number, row_num, col_num
FROM seats
WHERE coach_id = $1
ORDER BY row_num, col_num
`

func (q *Queries) ListSeatsByCoach(ctx context.Context, coachID string) ([]Seat, error) {
	rows, err := q.db.QueryContext(ctx, listSeatsByCoach, coachID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Seat
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.SeatNumber,
			&i.RowNum,
			&i.ColNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
