// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stations.sql

package db

import (
	"context"
)

const getStation = `-- name: GetStation :one
SELECT id, route_id, name, sequence_order, distance_from_origin_km
FROM stations
WHERE id = $1
`

func (q *Queries) GetStation(ctx context.Context, id string) (Station, error) {
	row := q.db.QueryRowContext(ctx, getStation, id)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.Name,
		&i.SequenceOrder,
		&i.DistanceFromOriginKm,
	)
	return i, err
}

const listStationsByRoute = `-- name: ListStationsByRoute :many
SELECT id, route_id, name, sequence_order, distance_from_origin_km
FROM stations
WHERE route_id = $1
ORDER BY sequence_order
`

func (q *Queries) ListStationsByRoute(ctx context.Context, routeID string) ([]Station, error) {
	rows, err := q.db.QueryContext(ctx, listStationsByRoute, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Station
	for rows.Next() {
		var i Station
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.Name,
			&i.SequenceOrder,
			&i.DistanceFromOriginKm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
