// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: train_schedules.sql

package db

import (
	"context"
)

const getSchedule = `-- name: GetSchedule :one
SELECT id, train_number, route_id, departure_time
FROM train_schedules
WHERE id = $1
`

func (q *Queries) GetSchedule(ctx context.Context, id string) (TrainSchedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, id)
	var i TrainSchedule
	err := row.Scan(
		&i.ID,
		&i.TrainNumber,
		&i.RouteID,
		&i.DepartureTime,
	)
	return i, err
}

const getScheduleByTrainNumber = `-- name: GetScheduleByTrainNumber :one
SELECT id, train_number, route_id, departure_time
FROM train_schedules
WHERE train_number = $1
`

func (q *Queries) GetScheduleByTrainNumber(ctx context.Context, trainNumber string) (TrainSchedule, error) {
	row := q.db.QueryRowContext(ctx, getScheduleByTrainNumber, trainNumber)
	var i TrainSchedule
	err := row.Scan(
		&i.ID,
		&i.TrainNumber,
		&i.RouteID,
		&i.DepartureTime,
	)
	return i, err
}

const listSchedulesByRoute = `-- name: ListSchedulesByRoute :many
SELECT id, train_number, route_id, departure_time
FROM train_schedules
WHERE route_id = $1
ORDER BY departure_time
`

func (q *Queries) ListSchedulesByRoute(ctx context.Context, routeID string) ([]TrainSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesByRoute, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainSchedule
	for rows.Next() {
		var i TrainSchedule
		if err := rows.Scan(
			&i.ID,
			&i.TrainNumber,
			&i.RouteID,
			&i.DepartureTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
