// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: train_journeys.sql

package db

import (
	"context"
	"time"
)

const getJourney = `-- name: GetJourney :one
SELECT id, schedule_id, travel_date, status
FROM train_journeys
WHERE id = $1
`

func (q *Queries) GetJourney(ctx context.Context, id string) (TrainJourney, error) {
	row := q.db.QueryRowContext(ctx, getJourney, id)
	var i TrainJourney
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.TravelDate,
		&i.Status,
	)
	return i, err
}

const getJourneyByScheduleAndDate = `-- name: GetJourneyByScheduleAndDate :one
SELECT id, schedule_id, travel_date, status
FROM train_journeys
WHERE schedule_id = $1 AND travel_date = $2
`

type GetJourneyByScheduleAndDateParams struct {
	ScheduleID string    `json:"schedule_id"`
	TravelDate time.Time `json:"travel_date"`
}

func (q *Queries) GetJourneyByScheduleAndDate(ctx context.Context, arg GetJourneyByScheduleAndDateParams) (TrainJourney, error) {
	row := q.db.QueryRowContext(ctx, getJourneyByScheduleAndDate, arg.ScheduleID, arg.TravelDate)
	var i TrainJourney
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.TravelDate,
		&i.Status,
	)
	return i, err
}

const listJourneysByDate = `-- name: ListJourneysByDate :many
SELECT id, schedule_id, travel_date, status
FROM train_journeys
WHERE travel_date = $1
ORDER BY status
`

func (q *Queries) ListJourneysByDate(ctx context.Context, travelDate time.Time) ([]TrainJourney, error) {
	rows, err := q.db.QueryContext(ctx, listJourneysByDate, travelDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainJourney
	for rows.Next() {
		var i TrainJourney
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.TravelDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
