// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: waitlist.sql

package db

import (
	"context"
)

const createWaitlistEntry = `-- name: CreateWaitlistEntry :one
INSERT INTO waitlist (
    journey_id, seat_id, board_station_id, alight_station_id,
    board_sequence, alight_sequence, passenger_name, passenger_email
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING
    id, journey_id, seat_id, board_station_id, alight_station_id,
    board_sequence, alight_sequence, passenger_name, passenger_email,
    status, created_at
`

type CreateWaitlistEntryParams struct {
	JourneyID       string `json:"journey_id"`
	SeatID          string `json:"seat_id"`
	BoardStationID  string `json:"board_station_id"`
	AlightStationID string `json:"alight_station_id"`
	BoardSequence   int32  `json:"board_sequence"`
	AlightSequence  int32  `json:"alight_sequence"`
	PassengerName   string `json:"passenger_name"`
	PassengerEmail  string `json:"passenger_email"`
}

func (q *Queries) CreateWaitlistEntry(ctx context.Context, arg CreateWaitlistEntryParams) (Waitlist, error) {
	row := q.db.QueryRowContext(ctx, createWaitlistEntry,
		arg.JourneyID,
		arg.SeatID,
		arg.BoardStationID,
		arg.AlightStationID,
		arg.BoardSequence,
		arg.AlightSequence,
		arg.PassengerName,
		arg.PassengerEmail,
	)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.JourneyID,
		&i.SeatID,
		&i.BoardStationID,
		&i.AlightStationID,
		&i.BoardSequence,
		&i.AlightSequence,
		&i.PassengerName,
		&i.PassengerEmail,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getWaitlistEntry = `-- name: GetWaitlistEntry :one
SELECT
    id, journey_id, seat_id, board_station_id, alight_station_id,
    board_sequence, alight_sequence, passenger_name, passenger_email,
    status, created_at
FROM waitlist
WHERE id = $1
`

func (q *Queries) GetWaitlistEntry(ctx context.Context, id string) (Waitlist, error) {
	row := q.db.QueryRowContext(ctx, getWaitlistEntry, id)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.JourneyID,
		&i.SeatID,
		&i.BoardStationID,
		&i.AlightStationID,
		&i.BoardSequence,
		&i.AlightSequence,
		&i.PassengerName,
		&i.PassengerEmail,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listWaitlistByJourney = `-- name: ListWaitlistByJourney :many
SELECT
    id, journey_id, seat_id, board_station_id, alight_station_id,
    board_sequence, alight_sequence, passenger_name, passenger_email,
    status, created_at
FROM waitlist
WHERE journey_id = $1
ORDER BY created_at
`

func (q *Queries) ListWaitlistByJourney(ctx context.Context, journeyID string) ([]Waitlist, error) {
	rows, err := q.db.QueryContext(ctx, listWaitlistByJourney, journeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Waitlist
	for rows.Next() {
		var i Waitlist
		if err := rows.Scan(
			&i.ID,
			&i.JourneyID,
			&i.SeatID,
			&i.BoardStationID,
			&i.AlightStationID,
			&i.BoardSequence,
			&i.AlightSequence,
			&i.PassengerName,
			&i.PassengerEmail,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWaitlistStatus = `-- name: UpdateWaitlistStatus :one
UPDATE waitlist
SET status = $2
WHERE id = $1
RETURNING
    id, journey_id, seat_id, board_station_id, alight_station_id,
    board_sequence, alight_sequence, passenger_name, passenger_email,
    status, created_at
`

type UpdateWaitlistStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateWaitlistStatus(ctx context.Context, arg UpdateWaitlistStatusParams) (Waitlist, error) {
	row := q.db.QueryRowContext(ctx, updateWaitlistStatus, arg.ID, arg.Status)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.JourneyID,
		&i.SeatID,
		&i.BoardStationID,
		&i.AlightStationID,
		&i.BoardSequence,
		&i.AlightSequence,
		&i.PassengerName,
		&i.PassengerEmail,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
